# Copyright 2026 PyHSS contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
from copy import deepcopy
import importlib.util,json
from pathlib import Path
import pytest
from sqlalchemy import select,insert,update,event
from cx_provisioning import CxProvisioning
from cx_repository import CxError
from pyhss_config import config
from test_cx_api_provisioning import bundle,associated_publics
from test_cx_registration import lab,REALM,digits,request,result,mar,sar,snapshot

def tool():
    path=Path(__file__).resolve().parents[1]/'tools/restore_cx_client_identities.py'
    spec=importlib.util.spec_from_file_location('identity_restore',path)
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module

def old_generated_profile(d):
    svc=CxProvisioning(d.database,config);payload=bundle(d)
    payload['ims_subscriber']['msisdn_list']=[digits(11)]
    ims=svc.create_service(payload)['ims_subscriber'];definition=deepcopy(ims['cx']);ident=ims['ims_subscriber_id']
    marked={}
    for item in definition['public_identities']:
        if item['identity'].startswith('sip:+'):
            marked[item['identity']]=item['identity']+';user=phone';item['identity']+=';user=phone'
    definition['provisioning']['managed_public']=[marked.get(x,x) for x in definition['provisioning']['managed_public']]
    # Seed rows generated by the prior version, including four lookup aliases.
    with svc.repo.transaction([ident]) as c:
        svc.repo.provision(ident,definition,replace=True,connection=c)
        c.execute(insert(svc.repo.identities),[{'identity':x,'kind':'private','ims_subscriber_id':ident} for x in definition['digest_identity_aliases']])
    return svc,ims,definition

def rows(repo,ident):
    with repo.engine.connect() as c:
        return sorted((r.identity,r.kind) for r in c.execute(select(repo.identities).where(repo.identities.c.ims_subscriber_id==ident)))

def test_restore_matches_failed_trace_shape_preserves_single_digest_auth_and_dereg(lab):
    d,_=lab;svc,ims,old=old_generated_profile(d);repo=svc.repo;ident=ims['ims_subscriber_id']
    private=old['provisioning']['private_identity'];lookup=next(iter(old['digest_identity_aliases']))
    public='sip:'+lookup
    avps,_=request(d,300,lookup,public);assert result(d,avps)==('experimental',5001)
    before=rows(repo,ident);assert len(before)==10
    review=tool().restore(repo,[ident]);assert review[0]['index_rows_after']==6
    assert rows(repo,ident)==before and not review[0]['applied']
    tool().restore(repo,[ident],apply=True)
    after=rows(repo,ident);assert len(after)==6
    assert [x for x,k in after if k=='private']==[private]
    avps,_=request(d,300,lookup,public);assert result(d,avps)==('experimental',2001)
    assert snapshot(d,private,public)['scscf'] is None
    avps,_=mar(d,lookup,public);assert result(d,avps)==('base',2001)
    assert bytes.fromhex(d.get_avp_data(avps,1)[0]).decode()==private
    avps,_=sar(d,1,lookup,public);assert result(d,avps)==('experimental',5002)
    avps,_=sar(d,1,private,public);assert result(d,avps)==('base',2001)
    assert not d.get_avp_data(avps,632)
    assert public in associated_publics(d,avps)
    assert not any(';user=phone' in x for x in associated_publics(d,avps))
    assert not any(x.startswith('sip:'+lookup.lstrip('+')) for x in associated_publics(d,avps))
    avps,_=sar(d,5,private,public);assert result(d,avps)==('base',2001)
    assert snapshot(d,private,public)['scscf'] is None
    assert not tool().restore(repo,[ident],apply=True)[0]['changed']

def test_native_api_edit_restores_managed_uri_and_barring_without_manual_db_provisioning(lab):
    d,_=lab;svc,ims,old=old_generated_profile(d);ident=ims['ims_subscriber_id']
    # Operator barring must survive the change in the managed identity spelling.
    item=next(x for x in old['public_identities'] if x['identity'].startswith('sip:+'));item['barred']=True
    with svc.repo.transaction([ident]) as c:
        c.execute(update(svc.repo.profiles).where(svc.repo.profiles.c.ims_subscriber_id==ident).values(definition=json.dumps(old)))
    updated=svc.save({'cx':{'authentication':'sip_digest'}},ident)['cx']
    assert next(x for x in updated['public_identities'] if x['identity']==item['identity'][:-len(';user=phone')])['barred']
    assert len(rows(svc.repo,ident))==6

def test_explicit_uri_parameters_remain_intact_unless_operator_selects_restoration(lab):
    d,_=lab;svc,ims,old=old_generated_profile(d)
    explicit='sip:+'+digits(11)+'@'+REALM+';user=phone'
    local='sip:'+digits(4)+';phone-context='+REALM+'@'+REALM+';user=phone'
    for identity in (explicit,local):old['public_identities'].append({'identity':identity,'set_id':'fixed','barred':True,'private_identities':old['private_identities']})
    old['provisioning']['additional_public_identities']=[{'identity':explicit},{'identity':local}]
    restored,mapping=tool().restored_definition(old)
    assert explicit not in mapping and local not in mapping
    restored,mapping=tool().restored_definition(old,include_explicit=True)
    assert explicit in mapping and local not in mapping
    assert next(x for x in restored['public_identities'] if x['identity']==mapping[explicit])['barred']
    assert restored['provisioning']['additional_public_identities'][0]['identity']==mapping[explicit]

def test_batch_restoration_rolls_back_if_one_subscription_is_assigned(lab):
    d,_=lab;svc,first,_=old_generated_profile(d);_,second,old=old_generated_profile(d)
    private=old['provisioning']['private_identity'];public=next(x['identity'] for x in old['public_identities'] if x['identity'].startswith('sip:+'))
    mar(d,private,public);sar(d,1,private,public)
    ids=[first['ims_subscriber_id'],second['ims_subscriber_id']];before=[rows(svc.repo,i) for i in ids]
    with pytest.raises(ValueError,match='De-register'):tool().restore(svc.repo,ids,apply=True)
    assert [rows(svc.repo,i) for i in ids]==before

def test_indexed_lookup_does_not_scan_all_provisioned_subscriptions(lab):
    d,_=lab;svc=CxProvisioning(d.database,config);ims=svc.create_service(bundle(d))['ims_subscriber'];repo=svc.repo
    private=ims['cx']['provisioning']['private_identity'];public=next(x['identity'] for x in ims['cx']['public_identities'] if x['identity'].startswith('sip:+'))
    statements=[]
    def capture(conn,cursor,statement,parameters,context,executemany):statements.append(statement)
    event.listen(repo.engine,'before_cursor_execute',capture)
    try:
        repo.resolve(public,private);assert len(statements)==2
        statements.clear()
        with repo.engine.connect() as c:
            with pytest.raises(CxError):repo.find('sip:missing-'+digits(5)+'@'+REALM,'public',c)
        assert len(statements)==2
        assert 'LEFT OUTER JOIN' in statements[-1]
    finally:event.remove(repo.engine,'before_cursor_execute',capture)

def test_diagnostics_understands_scoped_lookup_alias_without_a_private_index_row(lab):
    from test_cx_diagnostics import diagnostics
    d,_=lab;svc=CxProvisioning(d.database,config);ims=svc.create_service(bundle(d))['ims_subscriber']
    lookup=next(iter(ims['cx']['digest_identity_aliases']));private=ims['cx']['provisioning']['private_identity']
    report=diagnostics.diagnose(svc.repo.engine,lookup,'sip:'+lookup)
    assert report['private_identity']['role']=='digest_lookup_alias'
    assert report['identity_association']=='valid' and report['digest_authentication_identity']==private
    assert report['native_credential_link']=='valid'

def test_explicit_pending_cancellation_keeps_credentials_and_rejects_registered_state(lab):
    d,_=lab;svc,ims,old=old_generated_profile(d);ident=ims['ims_subscriber_id'];private=old['provisioning']['private_identity']
    public=next(x['identity'] for x in old['public_identities'] if x['identity'].startswith('sip:+'))
    with svc.repo.engine.connect() as c:before=list(c.execute(select(svc.repo.auc)))
    mar(d,private,public)
    with pytest.raises(ValueError,match='De-register'):tool().restore(svc.repo,[ident],apply=True)
    tool().restore(svc.repo,[ident],apply=True,clear_authentication_pending=True)
    assert snapshot(d,private,public[:-len(';user=phone')])['scscf'] is None
    with svc.repo.engine.connect() as c:assert list(c.execute(select(svc.repo.auc)))==before
    svc,ims,old=old_generated_profile(d);ident=ims['ims_subscriber_id'];private=old['provisioning']['private_identity']
    public=next(x['identity'] for x in old['public_identities'] if x['identity'].startswith('sip:+'))
    mar(d,private,public);sar(d,1,private,public)
    with pytest.raises(ValueError,match='Cannot clear'):tool().restore(svc.repo,[ident],apply=True,clear_authentication_pending=True)

def test_restore_conflicting_uri_policies_requires_operator_review(lab):
    d,_=lab;_,_,old=old_generated_profile(d)
    marked=next(x for x in old['public_identities'] if x['identity'].startswith('sip:+'))
    bare=deepcopy(marked);bare['identity']=bare['identity'][:-len(';user=phone')];bare['barred']=not marked['barred']
    old['public_identities'].append(bare)
    with pytest.raises(ValueError,match='merge existing identities'):tool().restored_definition(old)

def test_cli_default_is_read_only_without_schema_initialization(lab,monkeypatch,capsys):
    import database,sys
    d,_=lab;svc,ims,_=old_generated_profile(d);repo=svc.repo;ident=ims['ims_subscriber_id'];before=rows(repo,ident)
    module=tool();statements=[]
    monkeypatch.setattr(database,'database_connection_settings',lambda cfg:(repo.engine.url,{}))
    monkeypatch.setattr(module,'create_engine',lambda *a,**kw:repo.engine)
    monkeypatch.setattr(sys,'argv',['restore_cx_client_identities.py','--ims-subscriber-id',str(ident)])
    def capture(conn,cursor,statement,parameters,context,executemany):statements.append(statement)
    event.listen(repo.engine,'before_cursor_execute',capture)
    try:module.main()
    finally:event.remove(repo.engine,'before_cursor_execute',capture)
    assert '"mode": "dry-run"' in capsys.readouterr().out
    assert all(not sql.lstrip().upper().startswith(('CREATE','ALTER','INSERT','UPDATE','DELETE','DROP')) for sql in statements)
    assert rows(repo,ident)==before
